### ISSUE TITLE
tests::registry_start_app::start_app_* fails because of exec format error

### ISSUE THREAD

**Issue by minecraft2048** [kubos/kubos#550] opened 2020-06-28 05:24 UTC
**Description**
tests::registry_start_app::start_app_* fails because of exec format error, which is caused by leading spaces in the test script tiny-app 

**System Details**
- Host PC running Ubuntu 20.04 LTS
- Kubos git master

**Severity**
- Mild

**To Reproduce**
1. Run `cargo test --package kubos-app-service` in kubos directory
2. See test fails

**Bug Output**
```
byakuya@seireitei ~/D/kubos (master) [101]> cargo test --package kubos-app-service
   Compiling kubos-app-service v0.1.0 (/home/byakuya/Development/kubos/services/app-service)
    Finished dev [unoptimized + debuginfo] target(s) in 5.64s
     Running target/debug/deps/kubos_app_service-702543978e187954

running 29 tests
test tests::ping ... ok
test tests::register_app::register_bad_name ... ok
test tests::register_app::register_archive_no_extension ... ok
test tests::register_app::register_good ... ok
test tests::register_app::register_bad_path ... ok
test tests::register_app::register_duplicate ... ok
test tests::register_app::register_archive_wrong_extension ... ok
test tests::register_app::register_no_author ... ok
test tests::register_app::register_good_exec ... ok
test tests::registry_start_app::start_app_bad ... ok
test tests::register_app::register_no_active ... ok
test tests::register_app::register_good_config ... ok
test tests::registry_start_app::start_app_fail ... ok
test tests::register_app::register_no_version ... ok
test tests::register_app::register_no_manifest ... ok
test tests::register_app::register_no_name ... ok
test tests::registry_test::serialize_entry ... ok
test tests::registry_test::empty_apps_dir_empty_reg ... ok
test tests::registry_test::invalid_apps_dir_empty_reg ... ok
test tests::register_app::register_archive_bad_structure ... ok
test tests::register_app::register_good_archive ... ok
test tests::registry_test::custom_apps_dir ... ok
test tests::registry_start_app::start_app_good ... FAILED
test tests::set_version::set_version_bad ... ok
test tests::upgrade_app::upgrade_bad ... ok
test tests::set_version::set_version_good ... ok
test tests::registry_start_app::start_app_nonzero_rc ... FAILED
test tests::set_version::set_version_same ... ok
test tests::upgrade_app::upgrade_good ... ok

failures:

---- tests::registry_start_app::start_app_good stdout ----
Result: Err(StartError { err: "Failed to spawn app: Os { code: 8, kind: Other, message: \"Exec format error\" }" })
thread 'tests::registry_start_app::start_app_good' panicked at 'assertion failed: result.is_ok()', services/app-service/src/tests/registry_start_app.rs:78:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

---- tests::registry_start_app::start_app_nonzero_rc stdout ----
thread 'tests::registry_start_app::start_app_nonzero_rc' panicked at 'assertion failed: `(left == right)`
  left: `StartError { err: "Failed to spawn app: Os { code: 8, kind: Other, message: \"Exec format error\" }" }`,
 right: `StartError { err: "App returned exit code: 1" }`', services/app-service/src/tests/registry_start_app.rs:217:5


failures:
    tests::registry_start_app::start_app_good
    tests::registry_start_app::start_app_nonzero_rc

test result: FAILED. 27 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p kubos-app-service --bin kubos-app-service'
```

**Workaround**
After adding a delay in the tests::registry_start_app::start_app_nonzero_rc (for example), I can copy tiny-app executable, and I found this from hexedit:

```
00000000   0A 20 20 20  20 20 20 20  20 20 20 20  20 23 21 2F  62 69 6E 2F  62 61 73 68  0A 20 20 20  20 20 20 20  20 20 20 20  .            #!/bin/bash.
00000024   20 65 78 69  74 20 31 0A  20 20 20 20  20 20 20 20  20 20 20 20                                                       exit 1.
```

Because the several first characters isn't a shebang line, Linux get confused and it thinks its not a executable script. If I edit line 180 in https://github.com/kubos/kubos/blob/master/services/app-service/src/tests/registry_start_app.rs , I change it from 
```
        let src = r#"
            #!/bin/bash
            exit 1
            "#;
```
to 
```
        let src = r#"#!/bin/bash
            exit 1
            "#;
```
removing the leading spaces,  tests::registry_start_app::start_app_nonzero_rc passes
EDIT:
uninstall_all_unmonitor also have the same problem, coming from https://github.com/kubos/kubos/blob/master/services/app-service/tests/utils/mod.rs#L103

**Comment by Ropes** [comment] 2022-12-13 18:25
I have not been able to reproduce on `master` since @marshall updated the bash script to be defined in a format!(...) call. Closing, if you find it's not fixed feel free to reopen.

**Closed by Ropes** 2022-12-13 18:25 UTC
Labels: bug
